### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by Alex4210987** [RuijieWu/HUST-Course_selection_system_Fucker#2]
能否同时选所有艺术类课程？

**Comment by 7erryX** [comment]
可以的，而且很简单，多抓一些课程的包，把它们的DATA字段记录下来与对应课程名一起打成字典，然后每次发包把每个课程都发一遍就行，这也能更好的利用程序的多线程设计，或者还可以加入异步或用Go语言重写进一步提高性能。不过这不在我的需求范围内，只能期待pr了 :P

**Comment by Alex4210987** [comment]
好的喵，有空写

**Comment by Alex4210987** [comment]
我pr了，但是疑似有点小bug。但是由于我已经用这个repo（https://github.com/xhzq233/HUSTGrabClass）抢到课了，所以我也懒得改。后来者要用自己改改。

**Comment by Alex4210987** [comment]
我pr了，但是疑似有点小bug。但是由于我已经用这个repo
https://github.com/xhzq233/HUSTGrabClass
抢到课了，所以我也懒得改。后来者要用自己改改。
