### ISSUE TITLE
课程id优化

### ISSUE THREAD

**Issue by AlexEisie** [RuijieWu/HUST-Course_selection_system_Fucker#7]
目录列表里用正则表达式获取艺术类课程参数，检查了一下一个课程必须的参数是课程id，课堂id，课堂学分，课堂容量和课堂当前人数，其余可忽略。回显可以用python自带的decode解密response

**Comment by 7erryX** [comment]
我复述一下你的issue，我理解的是你认为
- 可以发包并用正则表达式匹配并获取艺术类课程参数以免要手动添加 [1]
- `课程必须的参数是课程id，课堂id，课堂学分，课堂容量和课堂当前人数，其余可忽略`
- 回显用decode解码字节流为字符串[2]

如果我有哪里理解有误的话希望你能告诉我，而在我上述的理解中，令我感到疑惑与不解的是
- 艺术类课程参数所处的文件我们还没有定位，你打算采取什么方案实现[1]?
- 我们的测试结果是只有两个ID是必要的，如果发生改变了我们下一次更新添加劳动教育抢课功能时会尝试重新测试确认并简化请求头
- 有哪里需要用到[2]这一步吗？

**Comment by AlexEisie** [comment]
好好好，周一早上没课回issue。选课页面中，需要使用'按照课堂分类'，在参数中加上分类+page就可以获取到课程列表。如果不添加课堂容量和当前人数，似乎会直接判定已满(你和我的测试结果冲突了，这点存疑)。回显可以判断当前状态，如cookie过期，选课成功，系统关闭等

**Comment by 7erryX** [comment]
- `回显可以判断当前状态，如cookie过期，选课成功，系统关闭等` 这实际上已经实现了，而且不需要手动decode😈

关于第一个问题，我实际上的疑问是，课堂与课程编号在html页面里吗，在编写脚本的时候我感觉这些参数会在js文件里因此还没有测试过。同时，课堂编号以外的参数应该是不会随着年份改变而改变的，直接打成一个本地的字典就可以免去运行程序去获取这些参数这一步骤，这也是README的Todo里提到人工缓存这些参数的原因。因此我们尚无计划去实现你提到的自动获取这些参数值的这一步，你如果感兴趣的话欢迎pr

**Comment by AlexEisie** [comment]
没啥，哥们这学期又没抢到艺术类，按照我写的脚本提供点思路而已。那个课程列表实际上抓包就能把请求抓出来，没记错的话好像是aspx之类的，实际上就写在选课按钮附近。我倒是做了一个字典但是没抢到急了就给删了，下学期重来Ծ‸Ծ
